PRODUCT_VERSION_MAJOR := 13
PRODUCT_VERSION_MINOR := 1
PRODUCT_VERSION_TAG := Stable

TARGET_PRODUCT_SHORT := $(shell echo "$(TARGET_PRODUCT)" | cut -d'_' -f 2,3)
PROTON_HOST_TIME := $(shell date -u +%Y%m%d-%H%M%S)

PROTON_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(PRODUCT_VERSION_TAG)

PROTON_BUILD_VARIANT ?= COMMUNITY

PROTON_BUILD := ProtonPlus-$(PROTON_VERSION)-$(TARGET_PRODUCT_SHORT)-$(PROTON_BUILD_VARIANT)-Vanilla-$(PROTON_HOST_TIME)
ifeq ($(WITH_GAPPS), true)
PROTON_BUILD := ProtonPlus-$(PROTON_VERSION)-$(TARGET_PRODUCT_SHORT)-$(PROTON_BUILD_VARIANT)-$(PROTON_HOST_TIME)
endif
RELEASE_TYPE := $(PROTON_BUILD_VARIANT)
