PRODUCT_VERSION_MAJOR := 13
PRODUCT_VERSION_MINOR := 02
PRODUCT_VERSION_TAG := Stable

TARGET_PRODUCT_SHORT := $(shell echo "$(TARGET_PRODUCT)" | cut -d'_' -f 2,3)
PROTON_HOST_TIME := $(shell date -u +%Y%m%d-%H%M%S)

PROTON_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(PRODUCT_VERSION_TAG)

ifeq ($(PROTON_BUILD_VARIANT),OFFICIAL)
    PROTON_BUILD := ProtonPlus-$(PROTON_VERSION)-$(TARGET_PRODUCT_SHORT)-OFFICIAL-$(PROTON_HOST_TIME)
    RELEASE_TYPE := OFFICIAL
else
    PROTON_BUILD := ProtonPlus-$(PROTON_VERSION)-$(TARGET_PRODUCT_SHORT)-UNOFFICIAL-$(PROTON_HOST_TIME)
    RELEASE_TYPE := UNOFFICIAL
endif
